4º/Web With Microservices/IW - Macarronya - Backend/amazdont/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path("accounts/", include("django.contrib.auth.urls"))

    # accounts/login / [name = 'login']
    # accounts/logout / [name= 'logout']
    # accounts/password_change / [name= 'password_change']
    # accounts/password_change/done / [name= 'password_change_done']
    # accounts/password_reset / [name= 'password_reset']
    # accounts/password_reset/done / [name= 'password_reset_done']
    # accounts/reset/<uidb64 > / < token > / [name = 'password_reset_confirm']
    # accounts/reset/done / [name= 'password_reset_complete']
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

4º/Web With Microservices/IW - Macarronya - Backend/web/urls.py
from django.urls import path
from . import views
from .view import product

app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),

    # Register
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),

    # Products
    path('products/create', product.create, name='product_create'),
    path('products/<int:id>', product.details, name='product_details'),
    path('products/<int:id>/update', product.update, name='product_update'),
    path('products/<int:id>/delete', product.delete, name='product_delete'),
    path('products/<int:id>/buy', product.buy, name='product_buy'),

    # Search
    path('search/', views.search, name='search')
]

4º/Web With Microservices/IW - Macarronya - Backend/web/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    userId = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    price = models.FloatField(default=0)
    status = models.IntegerField(default=0)
    # 0=OnSale, 1=Selled
    image = models.ImageField(upload_to='images', null=True, blank=True)

    def __str__(self):
        return self.name

4º/Web With Microservices/IW - Macarronya - Backend/web/forms.py
from django import forms
from .models import Product
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product

        fields = [
            "name",
            "description",
            "price",
            "image"
        ]


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

4º/Web With Microservices/IW - Macarronya - Backend/web/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from web.forms import NewUserForm
from web.models import Product
from .models import Product

import logging
logger = logging.getLogger(__name__)


def index(request):
    context = {}
    context["products"] = Product.objects.all().filter(
        status=0).order_by("-id")[:2]
    return render(request, 'web/index.html', context)


def search(request):
    query_dict = request.GET  # this is a dictionary
    query = query_dict.get("query")
    products = Product.objects.all().filter(name__icontains=query).filter(status=0)
    context = {"products": products}
    return render(request, 'web/product/search.html', context)


def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("web:index")
        messages.error(
            request, form.errors)
    form = NewUserForm()
    return render(request=request, template_name="registration/register.html", context={"form": form})


@login_required
def profile(request):
    context = {}
    context["products"] = Product.objects.filter(userId=request.user)
    return render(request, 'registration/profile.html', context)

4º/Web With Microservices/IW - Macarronya - Backend/web/templates/web/base.html
<html>

<head>
    <title>Amazdont</title>

    {% load static %}
    <link rel="icon" href="{% static 'media/logo.png' %}">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'web/style.css' %}">
</head>

<body style="padding-bottom: 4em;">
    {% if messages %}
    {% for message in messages %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-danger" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    {% include 'web/header.html' %}
    <div class="container-fluid" width="95%">
        {% block content %}{% endblock %}
    </div>
</body>

{% include 'web/footer.html' %}

</html>

4º/Web With Microservices/IW - Macarronya - Backend/web/templates/web/footer.html
<footer class="bg-light text-center text-lg-start;">
    <a class="container-fluid p-0">
        <div class="row">
            <a class="col text-center">
                Carril Novoa, Alexandre
            </a>

            <a class="col text-center">
                Dominguez Arjona, Julio
            </a>

            <a class="col text-center">
                Fernandez Vazquez, Alejandro
            </a>

            <a class="col text-center">
                Piatti, Vittoria
            </a>
        </div>
    </a>

    <div class="text-center p-0" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2023 Copyright:
        <a class="text-dark" href="https://mdbootstrap.com/">Amazdon't</a>
    </div>

</footer>

4º/Web With Microservices/IW - Macarronya - Backend/web/templates/web/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand" href="{% url 'web:index' %}">
        {% load static %}
        <img src="{% static 'media/logo.png' %}" alt="My image" width="50" height="auto">
        <link rel="stylesheet" href="{% static 'web/footer.css' %}">
    </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'web:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'web:product_create' %}">Create Product</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'web:profile' %}">Profile</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'web:register' %}">Register</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
            {% endif %}

        </ul>
    </div>
</nav>

4º/Web With Microservices/IW - Macarronya - Backend/web/templates/web/index.html
{% extends "web/base.html" %}
{% block content %}

{% load static %}

<div class="text-center">
    <img src="{% static 'media/logo.png' %}" alt="My image" width="250" height="auto">
</div>

<div class="container">

    <div class="row d-flex justify-content-center align-items-center">

        <div class="col-md-6">

            <br />

            <form method="GET" action="{% url 'web:search' %}" class="form-inline my-2 my-lg-0">
                <input type="text" class="searchInput" name="query" placeholder="" aria-label="Search" id="search">
                <button type="submit" class="searchButton">Search</button>
            </form>

            <br />

            {% for product in products %}

            <div class="boxOrange">
                <table>
                    {% if product.image %}
                    <td>
                        <img src="{{product.image.url}}" class="img-thumbnail" width="100" height="100">
                    </td>
                    {% endif %}

                    <td>
                        {{ product.user }}
                        <b> {{ product.name }} </b> <br />
                        $&nbsp{{ product.price }}<br />

                        <a href="{% url 'web:product_details' id=product.id %}">
                            <button class="actionButton">Description</button>
                        </a>
                    </td>
                </table>
            </div>


            {% endfor %}
            {% endblock %}

        </div>
    </div>
</div>

4º/Web With Microservices/IW - Macarronya - Backend/web/templates/web/product/create.html
{% extends "web/base.html" %}

{% block content %}
{% load static %}

<div class="row d-flex justify-content-left align-items-center" style="padding-left: 2%;">
    <div class="col-md-6">

        <br />
        <h2>Add a new product</h2>
        <br />

        <form method="POST" class="boxBlack" enctype="multipart/form-data">

            <!-- Security token -->
            {% csrf_token %}

            <!-- Using the formset -->
            {{ form.as_p }}
            <input type="hidden" value="1" id="user_id">

            <button type="submit" class="actionButton">Submit</button>
        </form>

        {% endblock %}
    </div>
</div>

4º/Web With Microservices/IW - Macarronya - Backend/web/templates/web/product/delete.html
{% extends "web/base.html" %}
{% block content %}

<div class="main">
    <!-- Create a Form -->
    <form method="POST" enctype="multipart/form-data">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you want to delete this item ?
        <input type="submit" value="Yes" />
        <a href="{% url 'web:index' %}">Cancel </a>
    </form>
</div>

{% endblock %}

4º/Web With Microservices/IW - Macarronya - Backend/web/templates/web/product/details.html
{% extends "web/base.html" %}
{% block content %}

{% load static %}

<div class="row d-flex justify-content-left align-items-center" style="padding-left: 2%;">
    <div class="col-md-6">

        <br />
        <h2>Product Info</h2>
        <br />

        <p class="boxOrange" style="width:fit-content; padding-right: 5%;">
            <b> {{ product.name }} </b>
        </p>

        <p class="boxOrange">
            Description: {{ product.description }}<br />
            $&nbsp{{ product.price }}<br />


            {% if product.status == 0 %}
            <a href="{% url 'web:product_buy' id=product.id %}">
                <button class="actionButton">Buy</button>
            </a>
            {% else %}
            SOLD
            {% endif %}
        </p>


    </div>
    {% if product.image %}
    <div class="col">
        <img src="{{product.image.url}}" class="img-thumbnail" width="250" height="250">
    </div>
    {% endif %}
    {% endblock %}
</div>

4º/Web With Microservices/IW - Macarronya - Backend/web/templates/web/product/search.html
{% extends "web/base.html" %}
{% block content %}

{% load static %}

<div class="row d-flex justify-content-left align-items-center" style="padding-left: 2%;">
    <div class="col-md-6">

        <br />

        <form method="GET" action="{% url 'web:search' %}" class="form-inline my-2 my-lg-0" style="width: 80%;">
            <input type="text" class="searchInput" name="query" placeholder="" aria-label="Search" id="search">
            <button type="submit" class="searchButton">Search</button>
        </form>

        <br />

        {% for product in products %}

        <br>

        <div class="boxOrange" class="container-flex">


            {% if product.image %}
            <div class="col">
                <img src="{{product.image.url}}" class="img-thumbnail" width="100" height="100">
            </div>
            {% endif %}

            <div class="col">
                {{ product.user }}
                <b> {{ product.name }}</b> <br />
                $&nbsp{{ product.price }}<br />

                <a href="{% url 'web:product_details' id=product.id %}">
                    <button class="actionButton">Description</button>
                </a>
            </div>



        </div>

        {% endfor %}
        {% endblock %}

    </div>
</div>

4º/Web With Microservices/IW - Macarronya - Backend/web/templates/web/product/update.html
{% extends "web/base.html" %}
{% block content %}
{% load static %}

<div class="row d-flex justify-content-left align-items-center" style="padding-left: 2%;">
    <div class="col-md-6">

        <br />
        <h2>Edit Product</h2>
        <br />

        <!-- Create a Form -->
        <form method="POST" class="boxBlack" enctype="multipart/form-data">
            <!-- Security token by Django -->
            {% csrf_token %}

            <!-- form as paragraph -->
            {{ form.as_p }}

            <button type="submit" class="actionButton">Update</button>
        </form>

        {% endblock %}

    </div>
</div>